import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { BadgeCheck, Heart, MapPin } from 'lucide-react';
import { Avatar } from '@/components/ui/Avatar';
import { Rating } from '@/components/ui/Badge';
import { getCategory } from '@/constants/categories';
import { cn, formatCurrency, truncate } from '@/utils';
export const ProfessionalCard = ({ professional, isFavorite, onToggleFavorite, variant = 'row', }) => {
    const category = getCategory(professional.specialty);
    if (variant === 'tile') {
        return (_jsxs(Link, { to: `/profissional/${professional.uid}`, className: "group relative w-[168px] shrink-0 overflow-hidden rounded-2xl border border-ink-100 bg-white p-3.5 shadow-soft transition-transform active:scale-[0.98]", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsx(Avatar, { name: professional.name, src: professional.photoURL, size: 48 }), professional.featured && (_jsx("span", { className: "rounded-full bg-ink-900 px-2 py-0.5 text-[9px] font-bold uppercase text-brand-yellow", children: "Top" }))] }), _jsx("p", { className: "mt-2.5 truncate text-sm font-bold", children: professional.name }), _jsx("p", { className: "truncate text-xs text-ink-400", children: category.name }), _jsxs("div", { className: "mt-2 flex items-center justify-between", children: [_jsx(Rating, { value: professional.rating, count: professional.reviewsCount, size: 12 }), professional.hourlyRate ? (_jsxs("span", { className: "text-[11px] font-bold text-ink-600", children: [formatCurrency(professional.hourlyRate), "/h"] })) : null] })] }));
    }
    return (_jsxs("div", { className: "flex items-start gap-3 rounded-2xl border border-ink-100 bg-white p-3.5 shadow-soft", children: [_jsx(Link, { to: `/profissional/${professional.uid}`, className: "shrink-0", children: _jsx(Avatar, { name: professional.name, src: professional.photoURL, size: 54 }) }), _jsxs(Link, { to: `/profissional/${professional.uid}`, className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("p", { className: "truncate text-[15px] font-bold", children: professional.name }), professional.approval === 'approved' && (_jsx(BadgeCheck, { size: 15, className: "shrink-0 fill-brand-yellow text-ink-900" }))] }), _jsx("p", { className: "text-xs font-semibold", style: { color: category.color }, children: category.name }), _jsx("p", { className: "mt-1 line-clamp-2 text-xs leading-relaxed text-ink-400", children: truncate(professional.description, 80) }), _jsxs("div", { className: "mt-2 flex items-center gap-3", children: [_jsx(Rating, { value: professional.rating, count: professional.reviewsCount, size: 13 }), _jsxs("span", { className: "flex items-center gap-1 text-[11px] text-ink-400", children: [_jsx(MapPin, { size: 11 }), professional.city] })] })] }), onToggleFavorite && (_jsx("button", { type: "button", "aria-label": isFavorite ? 'Remover dos favoritos' : 'Adicionar aos favoritos', onClick: () => onToggleFavorite(professional.uid), className: "shrink-0 rounded-full p-1.5 transition-colors hover:bg-ink-100", children: _jsx(Heart, { size: 18, className: cn(isFavorite ? 'fill-red-500 text-red-500' : 'text-ink-300') }) }))] }));
};
