import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Clock, MessageCircle } from 'lucide-react';
import { Avatar } from '@/components/ui/Avatar';
import { Badge, Rating } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { PROPOSAL_STATUS_LABELS, PROPOSAL_STATUS_STYLES } from '@/constants/categories';
import { formatCurrency, timeAgo } from '@/utils';
export const ProposalCard = ({ proposal, onAccept, onReject, onChat, showActions = false }) => (_jsxs("article", { className: "rounded-2xl border border-ink-100 bg-white p-4 shadow-soft", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Link, { to: `/profissional/${proposal.professionalId}`, className: "shrink-0", children: _jsx(Avatar, { name: proposal.professionalName, src: proposal.professionalPhoto, size: 44 }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsx(Link, { to: `/profissional/${proposal.professionalId}`, className: "truncate text-[15px] font-bold", children: proposal.professionalName }), _jsx("span", { className: "shrink-0 text-base font-extrabold", children: formatCurrency(proposal.price) })] }), _jsxs("div", { className: "mt-0.5 flex items-center gap-2.5", children: [_jsx(Rating, { value: proposal.professionalRating, size: 12 }), _jsxs("span", { className: "flex items-center gap-1 text-[11px] text-ink-400", children: [_jsx(Clock, { size: 11 }), proposal.estimatedDays, " ", proposal.estimatedDays === 1 ? 'dia' : 'dias'] })] })] })] }), _jsx("p", { className: "mt-3 rounded-xl bg-ink-50 px-3.5 py-3 text-[13px] leading-relaxed text-ink-600", children: proposal.message }), _jsxs("div", { className: "mt-3 flex items-center justify-between", children: [_jsx(Badge, { className: PROPOSAL_STATUS_STYLES[proposal.status], children: PROPOSAL_STATUS_LABELS[proposal.status] }), _jsx("span", { className: "text-[11px] text-ink-300", children: timeAgo(proposal.createdAt) })] }), showActions && proposal.status === 'pending' && (_jsxs("div", { className: "mt-3.5 flex gap-2", children: [onChat && (_jsx(Button, { variant: "outline", size: "sm", onClick: () => onChat(proposal), leftIcon: _jsx(MessageCircle, { size: 15 }), children: "Falar" })), onReject && (_jsx(Button, { variant: "ghost", size: "sm", onClick: () => onReject(proposal), children: "Recusar" })), onAccept && (_jsx(Button, { size: "sm", className: "flex-1", onClick: () => onAccept(proposal), children: "Aceitar proposta" }))] }))] }));
