import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Calendar, MapPin, MessageSquareQuote } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { CategoryBubble } from '@/components/ui/CategoryIcon';
import { SafeImage } from '@/components/ui/SafeImage';
import { REQUEST_STATUS_LABELS, REQUEST_STATUS_STYLES, URGENCY_LABELS, URGENCY_STYLES, getCategory, } from '@/constants/categories';
import { formatCurrency, formatDate, timeAgo, truncate } from '@/utils';
export const RequestCard = ({ request, to, showStatus = true }) => {
    const category = getCategory(request.categoryId);
    return (_jsxs(Link, { to: to, className: "block overflow-hidden rounded-2xl border border-ink-100 bg-white shadow-soft transition-transform active:scale-[0.99]", children: [_jsxs("div", { className: "flex gap-3 p-3.5", children: [_jsx(CategoryBubble, { categoryId: request.categoryId, size: 46, className: "shrink-0" }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsx("p", { className: "line-clamp-2 text-[15px] font-bold leading-snug", children: request.title }), _jsx("span", { className: "shrink-0 text-sm font-extrabold text-ink-900", children: formatCurrency(request.budget) })] }), _jsx("p", { className: "mt-0.5 text-[11px] font-semibold", style: { color: category.color }, children: category.name }), _jsx("p", { className: "mt-1.5 line-clamp-2 text-xs leading-relaxed text-ink-400", children: truncate(request.description, 100) }), _jsxs("div", { className: "mt-2.5 flex flex-wrap items-center gap-1.5", children: [_jsx(Badge, { className: URGENCY_STYLES[request.urgency], children: URGENCY_LABELS[request.urgency] }), showStatus && (_jsx(Badge, { className: REQUEST_STATUS_STYLES[request.status], children: REQUEST_STATUS_LABELS[request.status] })), request.proposalsCount > 0 && (_jsxs(Badge, { icon: _jsx(MessageSquareQuote, { size: 11 }), children: [request.proposalsCount, " propostas"] }))] })] })] }), request.photos.length > 0 && (_jsx("div", { className: "flex gap-1.5 px-3.5 pb-3", children: request.photos.slice(0, 3).map((photo, index) => (_jsx(SafeImage, { src: photo, alt: `Foto ${index + 1}`, className: "h-16 w-24 rounded-xl" }, photo))) })), _jsxs("div", { className: "flex items-center justify-between border-t border-ink-100 bg-ink-50/60 px-3.5 py-2 text-[11px] text-ink-400", children: [_jsxs("span", { className: "flex min-w-0 items-center gap-1", children: [_jsx(MapPin, { size: 11, className: "shrink-0" }), _jsx("span", { className: "truncate", children: request.address })] }), _jsxs("span", { className: "flex shrink-0 items-center gap-1", children: [_jsx(Calendar, { size: 11 }), formatDate(request.date)] })] }), _jsxs("div", { className: "px-3.5 pb-2 text-[10px] text-ink-300", children: ["Publicado ", timeAgo(request.createdAt)] })] }));
};
